[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  # Let Netlify use its default Python version

# If using Netlify Functions for Flask, you would add a [[redirects]] block here.
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/app/:splat"
#   status = 200 